### ISSUE TITLE
Add waitfor and docker depends db to docker-compose file

### ISSUE THREAD

**Issue by Bank-Builder** [GrindrodBank/dokuti#15]
**Reason for Feature Request**
When **docker-compose up** is run the order of availability of the services is indeterminate.  Dokuti fails to properly start if the DB service is not yet running, which may take milliseconds longer.  Dokuti itself might be better behaved and wait a bit longer while looking for the DB before failing to start.

**Desired solution**
(1) Change Dokuti to be more patient and look for DB service before just exiting on startup.
(2) Make the docker-compose file more robust by adding something like the docker docs suggest:
```
version: "2"
services:
  web:
    build: .
    ports:
      - "80:8000"
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--", "Echo 'DB is up. Good to proceed' "]
  db:
    image: postgres
```

The wait-for script has an MIT Licence and can be found here:
```
https://github.com/eficode/wait-for
```
**Workaround**
Just run **docker-compose up** again and since the DB will be now up, the Dokuti WEB service will now start ... very clunky.
